# hosts/expertbook/default.nix
# ExpertBook laptop configuration
# Host-specific settings go here; common settings are in modules/common
{ pkgs, config, ... }:
{
  imports = [
    ./hardware-configuration.nix  # Auto-generated by nixos-generate-config
    ./../../modules/common        # Common modules for all hosts
  ];

  # ====== LAPTOP-SPECIFIC PACKAGES ======
  environment.systemPackages = with pkgs; [
    acpi          # Battery info
    brightnessctl # Brightness control
    powertop      # Power analysis
  ];

  # ====== POWER MANAGEMENT ======
  services = {
    # Power profiles daemon (for power/balanced/performance modes)
    power-profiles-daemon.enable = true;

    # Battery monitoring
    upower = {
      enable = true;
      percentageLow = 20;
      percentageCritical = 5;
      percentageAction = 3;
      criticalPowerAction = "PowerOff";
    };

    # Thermal management
    thermald.enable = true;
  };

  # CPU governor (consider "powersave" for better battery)
  powerManagement.cpuFreqGovernor = "performance";

  # ====== LAPTOP KERNEL MODULES ======
  boot = {
    kernelModules = [ "acpi_call" ];
    extraModulePackages = with config.boot.kernelPackages; [
      acpi_call
    ];
  };
}
