# hosts/expertbook/hardware-configuration.nix
# PLACEHOLDER - This file will be auto-generated by nixos-generate-config during installation
# Do NOT edit manually - run: sudo nixos-generate-config --show-hardware-config > hardware-configuration.nix

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # ====== BOOT ======
  # For encrypted LUKS root partition
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];  # or "kvm-amd" for AMD
  boot.extraModulePackages = [ ];

  # ====== LUKS ENCRYPTION ======
  # This will be configured by the install script
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-partlabel/cryptroot";
    preLVM = true;
    allowDiscards = true;  # Enable TRIM for SSD
  };

  # ====== FILESYSTEMS ======
  # These will be auto-generated, but here's a template:
  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "ext4";
    # For btrfs, use: fsType = "btrfs"; options = [ "compress=zstd" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partlabel/EFI";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  # ====== HARDWARE ======
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
